"""new foreing key in blog to user id

Revision ID: 387aaa50bfc4
Revises: 4a45f317724c
Create Date: 2018-09-15 16:51:49.304585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387aaa50bfc4'
down_revision = '4a45f317724c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_admin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['blog_admin'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'blog_admin')
    # ### end Alembic commands ###
